/* *********************************************************************
 * This Original Work is copyright of 51 Degrees Mobile Experts Limited.
 * Copyright 2019 51 Degrees Mobile Experts Limited, 5 Charlotte Close,
 * Caversham, Reading, Berkshire, United Kingdom RG4 7BY.
 *
 * This Original Work is licensed under the European Union Public Licence (EUPL) 
 * v.1.2 and is subject to its terms as set out below.
 *
 * If a copy of the EUPL was not distributed with this file, You can obtain
 * one at https://opensource.org/licenses/EUPL-1.2.
 *
 * The 'Compatible Licences' set out in the Appendix to the EUPL (as may be
 * amended by the European Commission) shall be deemed incompatible for
 * the purposes of the Work and the provisions of the compatibility
 * clause in Article 5 of the EUPL shall not apply.
 * 
 * If using the Work as, or as part of, a network application, by 
 * including the attribution notice(s) required under Article 5 of the EUPL
 * in the end user terms of the application under an appropriate heading, 
 * such notice(s) shall fulfill the requirements of that article.
 * ********************************************************************* */

const evidenceKeyFilterBase = require("./evidenceKeyFilter");

class flowElement {

    /**
     * Constructor for flowElement class
     *
     * @param {Object} options
     * @param {String} options.dataKey the dataKey the flowElement's elementData will be stored under
     * @param {Function} options.processInternal callback to act on flowData
     * @param {Object} options.properties list of properties including metadata
     * @param {{Function(new:evidenceKeyFilter)}} options.evidenceKeyFilter an instance of an evidenceKeyFilter
    */
    constructor(
        {
            processInternal,
            dataKey,
            properties = {},
            evidenceKeyFilter

        } = {}) {

        this.dataKey = dataKey;

        if (processInternal) {

            this.processInternal = processInternal;

        }

        this.properties = properties;

        if (evidenceKeyFilter) {

            this.evidenceKeyFilter = evidenceKeyFilter;

        } else {

            this.evidenceKeyFilter = new evidenceKeyFilterBase();

        }

        this.registrationCallbacks = [];

        // List of pipelines the flowElement has been added to
        this.pipelines = [];

    }

    /**
     * Function to be called when a flowElement is added to pipeline, runs through any registrationCallbacks on the flowElement     
    * */
    onRegistration(pipeline, flowElement) {

        this.registrationCallbacks.forEach(function (registrationCallback) {

            registrationCallback(pipeline, flowElement);

        });

    }

    /**
     * Internal process function for a particular flowElement called (via the flowElement.process() method) when flowData generated by a pipleline is processsed. Overriden by instances of this base class
    */
    processInternal() {

        return true;

    }

    /**
     * To allow actions to take place before and after a flowElement's processInternal function runs, a process wrapper is run first
    */
    process(flowData) {

        return Promise.resolve(this.processInternal(flowData));

    }

    /**
     * Call this function to update the properties meta database in all the pipelines this flowElement has been added to
    */
    updateProperties() {

        let flowElement = this;

        let updates = [];

        this.pipelines.forEach(function (pipeline) {

            updates.push(pipeline.updatePropertyDataBaseForElement(flowElement));

        });

        return Promise.all(updates);

    }

    /**
     * Get a flowElement's properties. By default returns a promise wrapped version of the object's properties list
     * Can return standard value or promise
    */
    getProperties() {

        return this.properties;

    }

}

module.exports = flowElement;
