export const AspectData: typeof import("./aspectData");
export const AspectDataDictionary: typeof import("./aspectDataDictionary");
export const DataFile: typeof import("./dataFile");
export const DataKeyedCache: typeof import("./dataKeyedCache");
export const Engine: typeof import("./engine");
export const Lru: typeof import("./lru");
export const LruCache: typeof import("./lruCache");
export const MissingPropertyService: typeof import("./missingPropertyService");
// export const DataFileUpdateService: typeof import("./dataFileUpdateService");
export let AutoUpdateStatus: {
    AUTO_UPDATE_SUCCESS: string;
    AUTO_UPDATE_HTTPS_ERR: string;
    AUTO_UPDATE_NOT_NEEDED: string;
    AUTO_UPDATE_IN_PROGRESS: string;
    AUTO_UPDATE_MASTER_FILE_CANT_RENAME: string;
    AUTO_UPDATE_ERR_429_TOO_MANY_ATTEMPTS: string;
    AUTO_UPDATE_ERR_403_FORBIDDEN: string;
    AUTO_UPDATE_ERR_READING_STREAM: string;
    AUTO_UPDATE_ERR_MD5_VALIDATION_FAILED: string;
    AUTO_UPDATE_NEW_FILE_CANT_RENAME: string;
    AUTO_UPDATE_REFRESH_FAILED: string;
};
export let Tracker: typeof import("./tracker");
