name: Nightly Package Update


# Scheduled runs are temporarily disabled, because right now they cause
# an eternal cycle of dependency updates
on:
  workflow_dispatch:
    inputs:
      dryrun:
        default: false
        type: boolean
        description: Dry Run
#  schedule:
#    - cron: '0 0 * * *'


jobs:
  Nightly_Package_Update:
    uses: postindustria-tech/common-ci/.github/workflows/nightly-package-update.yml@main
    with:
      repo-name: ${{ github.event.repository.name }}
      org-name: ${{ github.event.repository.owner.login }}
      dryrun: ${{ inputs.dryrun || false }}
    secrets:
      token: ${{ secrets.ACCESS_TOKEN }}
